apiVersion: v1
kind: Secret
metadata:
  name: django-secret
  namespace: django-app
type: Opaque
stringData:
  SECRET_KEY: super-secret-key
  DATABASE_URL: postgres://myuser:mypassword@postgres:5432/mydb

